import { createStore } from 'vuex'
import { vuexLocalStorage } from './plugins/vuexPersistence'

export default createStore({
    state: {
        vacancies: [{
            "audio": "",
            "comments_count": 0,
            "company_id": 3501,
            "company_logo": "https://media.talentpitch.co/app/generics/companies/default_image_logo.png",
            "company_name": "TalentPitch Vacantes Externas",
            "compatibility": null,
            "compatibility_reason": null,
            "connected": false,
            "contract_type": "[{\"icon\":\"contract\",\"key\":\"to_be_agreed\",\"label\":\"To be agreed\"}]",
            "created_at": "09-10-2023",
            "creator": "",
            "description": "En este rol se requiere una persona con demasiada estructura, metodología, procesos, análisis de datos, geek, irreverente.",
            "desired_states": "[{\"icon\":\"https://media.interacpedia.com/app/work/want_first_job.svg\",\"key\":\"first_job\",\"label\":\"First job\"},{\"icon\":\"https://media.interacpedia.com/app/work/want_employment.svg\",\"key\":\"employment\",\"label\":\"Employment\"}]",
            "id": 491897,
            "image": "https://media.talentpitch.co/app/generics/thematics/tech/image_7.webp",
            "interest_areas": "software_development_and_programming",
            "level_experience": "3",
            "name": "DESARROLLADOR FRONTEND",
            "optional_requirements": "",
            "pitches_count": 0,
            "presentation": false,
            "proposed_count": 0,
            "requirements": "Vuex",
            "review": 0,
            "salary": "Confidential",
            "selected_count": 0,
            "sent_pitch": false,
            "video": "https://media.talentpitch.co/medias/ba2c3906-0c63-4d55-9387-30718a2f9964.webm",
            "views_count": 186,
            "work_methods": "[{\"icon\":\"work\",\"key\":\"remote\",\"label\":\"profile.remote\"}]"
        },
        {
            "audio": "",
            "comments_count": 0,
            "company_id": 3501,
            "company_logo": "https://media.talentpitch.co/app/generics/companies/default_image_logo.png",
            "company_name": "TalentPitch Vacantes Externas",
            "compatibility": null,
            "compatibility_reason": null,
            "connected": false,
            "contract_type": "",
            "created_at": "09-10-2023",
            "creator": "",
            "description": "En este rol se requiere una persona con demasiada estructura, metodología, procesos, análisis de datos, geek, irreverente.",
            "desired_states": "[{\"icon\":\"https://media.interacpedia.com/app/work/want_first_job.svg\",\"key\":\"first_job\",\"label\":\"First job\"},{\"icon\":\"https://media.interacpedia.com/app/work/want_employment.svg\",\"key\":\"employment\",\"label\":\"Employment\"}]",
            "id": 491895,
            "image": "https://media.talentpitch.co/app/generics/thematics/tech/image_2.webp",
            "interest_areas": "",
            "level_experience": "0",
            "name": "TRAFFICKER",
            "optional_requirements": "",
            "pitches_count": 0,
            "presentation": false,
            "proposed_count": 0,
            "requirements": "",
            "review": 0,
            "salary": "Confidential",
            "selected_count": 0,
            "sent_pitch": false,
            "video": "https://media.talentpitch.co/challenges/491895/tmpdirect-upload-v1-d8e3f0c7e7d24295801e4b6b2c651484.mp4",
            "views_count": 49,
            "work_methods": ""
        },
        {
            "audio": "",
            "comments_count": 0,
            "company_id": 3501,
            "company_logo": "https://media.talentpitch.co/app/generics/companies/default_image_logo.png",
            "company_name": "TalentPitch Vacantes Externas",
            "compatibility": null,
            "compatibility_reason": null,
            "connected": false,
            "contract_type": "",
            "created_at": "09-10-2023",
            "creator": "",
            "description": "En este rol se requiere una persona con demasiada estructura, metodología, procesos, análisis de datos, geek, irreverente.",
            "desired_states": "[{\"icon\":\"https://media.interacpedia.com/app/work/want_employment.svg\",\"key\":\"employment\",\"label\":\"Employment\"},{\"icon\":\"https://media.interacpedia.com/app/work/want_first_job.svg\",\"key\":\"first_job\",\"label\":\"First job\"}]",
            "id": 491899,
            "image": "https://media.talentpitch.co/app/generics/thematics/tech/image_9.webp",
            "interest_areas": "",
            "level_experience": "0",
            "name": "LÍDER INTELIGENCIA DE USUARIOS",
            "optional_requirements": "",
            "pitches_count": 0,
            "presentation": false,
            "proposed_count": 0,
            "requirements": "",
            "review": 0,
            "salary": "Confidential",
            "selected_count": 0,
            "sent_pitch": false,
            "video": "https://media.talentpitch.co/challenges/491899/tmpdirect-upload-v1-c73cf3a828e04bd2bd17f18f69545b99.mp4",
            "views_count": 52,
            "work_methods": ""
        },
        {
            "audio": "",
            "comments_count": 0,
            "company_id": 3501,
            "company_logo": "https://media.talentpitch.co/app/generics/companies/default_image_logo.png",
            "company_name": "TalentPitch Vacantes Externas",
            "compatibility": null,
            "compatibility_reason": null,
            "connected": false,
            "contract_type": "",
            "created_at": "10-10-2023",
            "creator": "",
            "description": "En este rol se requiere una persona con demasiada estructura, metodología, procesos, análisis de datos, geek, irreverente.",
            "desired_states": "[{\"icon\":\"https://media.interacpedia.com/app/work/want_employment.svg\",\"key\":\"employment\",\"label\":\"Employment\"},{\"icon\":\"https://media.interacpedia.com/app/work/want_first_job.svg\",\"key\":\"first_job\",\"label\":\"First job\"}]",
            "id": 491901,
            "image": "https://media.talentpitch.co/app/generics/thematics/tech/image_3.webp",
            "interest_areas": "",
            "level_experience": "0",
            "name": "COORDINADOR CX",
            "optional_requirements": "",
            "pitches_count": 0,
            "presentation": false,
            "proposed_count": 0,
            "requirements": "",
            "review": 0,
            "salary": "Confidential",
            "selected_count": 0,
            "sent_pitch": false,
            "video": "https://media.talentpitch.co/challenges/491901/tmpdirect-upload-v1-e4901a560a824529a255f1179ff3f1ff.mp4",
            "views_count": 31,
            "work_methods": ""
        },
        {
            "audio": "",
            "comments_count": 0,
            "company_id": 3501,
            "company_logo": "https://media.talentpitch.co/app/generics/companies/default_image_logo.png",
            "company_name": "TalentPitch Vacantes Externas",
            "compatibility": null,
            "compatibility_reason": null,
            "connected": false,
            "contract_type": "",
            "created_at": "09-10-2023",
            "creator": "",
            "description": "En este rol se requiere una persona con demasiada estructura, metodología, procesos, análisis de datos, geek, irreverente.",
            "desired_states": "[{\"icon\":\"https://media.interacpedia.com/app/work/want_first_job.svg\",\"key\":\"first_job\",\"label\":\"First job\"},{\"icon\":\"https://media.interacpedia.com/app/work/want_employment.svg\",\"key\":\"employment\",\"label\":\"Employment\"}]",
            "id": 491891,
            "image": "https://media.talentpitch.co/app/generics/thematics/rse/image_6.webp",
            "interest_areas": "",
            "level_experience": "0",
            "name": "COORDINADOR ADMINISTRATIVO",
            "optional_requirements": "",
            "pitches_count": 0,
            "presentation": false,
            "proposed_count": 0,
            "requirements": "",
            "review": 0,
            "salary": "Confidential",
            "selected_count": 0,
            "sent_pitch": false,
            "video": "https://media.talentpitch.co/challenges/491891/tmpdirect-upload-v1-a33dcc6bde914f75bcb716e80c21481a.mp4",
            "views_count": 76,
            "work_methods": ""
        },
        {
            "audio": "",
            "comments_count": 0,
            "company_id": 3501,
            "company_logo": "https://media.talentpitch.co/app/generics/companies/default_image_logo.png",
            "company_name": "TalentPitch Vacantes Externas",
            "compatibility": null,
            "compatibility_reason": null,
            "connected": false,
            "contract_type": "",
            "created_at": "05-10-2023",
            "creator": "",
            "description": "Experiencia en pruebas automatizadas con selenium|Manejo de bases de datos SQL, oracle, Sybase DB2About Our ClientNuentro cliente es una empresa de servicios de TI que utiliza el poder de la tecnología para construir un mejor futuro para sus clientes, colegas, el medio ambiente y las comunidades.Job DescriptionLa posición de Sr. QA Automation deberá:Desarrollar y mantener casos de prueba para un producto relevante,Ejecutar los casos y escenarios de prueba de todos los módulos principales y publica los resultados,Redactar y mantener los scripts de automatización de pruebas,Revisar las pruebas automatizadas y manuales, y sugiere opciones para mejorar la cobertura y la calidad,Identificar y notificar los defectos del software de forma adecuada y sigue el ciclo de vida de los defectos definido,Proporcionar la información necesaria para la planificación y ejecución de pruebas de regresión y del sistema,Comprender los requisitos empresariales proporcionados,Participar con todo el equipo en el establecimiento de las normas de calidad de un producto.The Successful ApplicantBuscamos tecnologos o estudiantes de carreras profesionales en Ingeniería de Sistemas o carrera afín con 1 a 2 años de experiencia en cargos similares de QA para importante empresa:Experiencia en la mejora del marco de pruebas de automatización, como Selenium, Rest Assured, pruebas APIExperiencia en SQL, oracle Sybase DB2Experiencia en microservicios,Familiarizado con el seguimiento de errores, como JIRA y TestRailDebe tener una gran capacidad de análisis de requisitos.What s on OfferTe ofrecemos contrato a termino indefinido y un excelente maletín de beneficios para ti y tu familia.Contact: Miguel RamirezQuote job ref: JN-042023-6030663      Mostrar más           Mostrar menos. Oferta publicada por Michael Page en Bogotá",
            "desired_states": "[{\"icon\":\"https://media.interacpedia.com/app/work/want_employment.svg\",\"key\":\"employment\",\"label\":\"Employment\"}]",
            "id": 491881,
            "image": "https://media.talentpitch.co/app/generics/thematics/default_tech-horizontal.png",
            "interest_areas": "",
            "level_experience": "2",
            "name": "Automatizador de pruebas JR",
            "optional_requirements": "",
            "pitches_count": 0,
            "presentation": false,
            "proposed_count": 0,
            "requirements": "capacidad, sistemas, servicios, redes, bases, datos, calidad, empresa, oracle, experiencia",
            "review": 0,
            "salary": "to agree",
            "selected_count": 0,
            "sent_pitch": false,
            "video": "",
            "views_count": 6,
            "work_methods": ""
        },
        {
            "audio": "",
            "comments_count": 0,
            "company_id": 3501,
            "company_logo": "https://media.talentpitch.co/app/generics/companies/default_image_logo.png",
            "company_name": "TalentPitch Vacantes Externas",
            "compatibility": null,
            "compatibility_reason": null,
            "connected": false,
            "contract_type": "",
            "created_at": "05-10-2023",
            "creator": "",
            "description": "Bekaert ( www.bekaert.com ) is a world market and technology leader in steel wire transformation and coating technologies. We pursue to be the preferred supplier for our steel wire products and solutions by continuously delivering superior value to our customers worldwide. Bekaert (Euronext Brussels: BEKB) is a global company with more than 27 000 employees worldwide, headquarters in Belgium and € 5.9 billion in combined revenue in 2021. Comprador Operacional ¡Sé parte de algo más grande!Bekaert es un líder mundial en el mercado y en tecnología de transformación de alambre de acero y tecnologías de revestimiento. Bekaert busca ser el proveedor preferido de productos y soluciones de alambre de acero al brindar continuamente un valor superior a nuestros clientes en todo el mundo. Somos una empresa global con más de 27000 empleados en todo el mundo, sede en Bélgica y 6 billones de euros en ingresos combinados. Acerca de la posicion El Comprador SSC (Shared Service Center) de compras impacta directamente en nuestro proceso productivo. Este rol reporta al Gerente de Categoría Regional. Y ofrece la oportunidad de desarrollar una carrera en compras con una empresa global. Tu impacto como Comprador SSC (Shared Service Center) Asegurar la disponibilidad de los bienes y servicios necesarios para el correcto desarrollo de las operaciones. Crear órdenes de compra para nuestros proveedores a través de los sistemas internos (SAP) e EBuy. Gestionar y resolver excepciones de entrega, calidad, precio y facturación oportunamente, apoyando la correcta ejecución del proceso de Procurement to Pay (P2P). Minimizar interrupciones de producción mediante la compra según las necesidades de MRP y la revisión táctica de la demanda. Realizar seguimiento a la confirmación y entrega de los pedidos. Participar en las reuniones con las plantas como representante de compras para proporcionar y recibir información sobre resolución de problemas. Acerca de ti Habilidades y competencias esenciales Formación en administración o carreras afines. Más de 2 años de experiencia en cadena de suministro o compras. Conocimiento técnico deseable de SAP u otros sistemas de planificación de recursos empresariales (ERP) Una buena comprensión técnica del proceso de comrpas es una ventaja. ¿Por qué unirse a nosotros? En Bekaert, estamos en un viaje para establecer lo nuevo posible. Y para lograrlo, necesitamos personas apasionadas que estén ansiosas por crecer más allá de sus capacidades. Queremos personas que sean valientes y estén dispuestas a explorar lo desconocido, incluso si eso significa fallar a veces. Personas que están dispuestas a aportar todo su ser al trabajo y no tienen miedo de expresar sus opiniones, pero que también valoran el poder de las sinergias, las diferentes perspectivas y el espíritu de equipo.Somos un empleador que ofrece igualdad de oportunidades y valoramos la diversidad en nuestra empresa. No discriminamos por motivos de raza, religión, color, origen nacional, sexo, género, expresión de género, orientación sexual, edad, estado civil, estado de veterano o estado de discapacidad.Visita nuesta pagina de empleos : Bekaert JobsYou grow, we grow... Better together. Bekaert offers continuous development opportunities.         Mostrar más           Mostrar menos. Oferta publicada por Bekaert en Bogotá",
            "desired_states": "[{\"icon\":\"https://media.interacpedia.com/app/work/want_employment.svg\",\"key\":\"employment\",\"label\":\"Employment\"}]",
            "id": 491867,
            "image": "https://media.talentpitch.co/app/generics/thematics/default_tech-horizontal.png",
            "interest_areas": "",
            "level_experience": "2",
            "name": "Comprador Operacional",
            "optional_requirements": "",
            "pitches_count": 0,
            "presentation": false,
            "proposed_count": 0,
            "requirements": "mercado, cadenadesuministro, sistemas, compras, servicios, desarrollar, world, cadena, recursos, trabajo",
            "review": 0,
            "salary": "to agree",
            "selected_count": 0,
            "sent_pitch": false,
            "video": "",
            "views_count": 0,
            "work_methods": ""
        },
        {
            "audio": "",
            "comments_count": 0,
            "company_id": 3501,
            "company_logo": "https://media.talentpitch.co/app/generics/companies/default_image_logo.png",
            "company_name": "TalentPitch Vacantes Externas",
            "compatibility": null,
            "compatibility_reason": null,
            "connected": false,
            "contract_type": "[{\"icon\":\"contract\",\"key\":\"to_be_agreed\",\"label\":\"To be agreed\"}]",
            "created_at": "29-09-2023",
            "creator": "",
            "description": "Fomentar la innovación y el compromiso de los empleados.\nMejorar la empresa y su visión a través de ideas frescas y soluciones prácticas.\nPotenciar el desarrollo profesional de nuestros colaboradores.",
            "desired_states": "[{\"icon\":\"https://media.interacpedia.com/app/work/want_employment.svg\",\"key\":\"employment\",\"label\":\"Employment\"}]",
            "id": 491857,
            "image": "https://media.talentpitch.co/medias/233e0d4f-be35-40c5-a8b9-f71d0bfc007c-horizontal.png",
            "interest_areas": "",
            "level_experience": "0",
            "name": "Convocatoria Masiva",
            "optional_requirements": "",
            "pitches_count": 0,
            "presentation": false,
            "proposed_count": 0,
            "requirements": "CreatividadeInnovación/, Compromiso, ConcienciadelaVisiónEmpresarial, ÉticayCumplimiento, CapacidadparaTrabajarenEquipo",
            "review": 0,
            "salary": "to agree",
            "selected_count": 0,
            "sent_pitch": false,
            "video": "",
            "views_count": 29,
            "work_methods": "[{\"icon\":\"work\",\"key\":\"to_be_agreed\",\"label\":\"To be agreed\"}]"
        },
        {
            "audio": "",
            "comments_count": 0,
            "company_id": 3501,
            "company_logo": "https://media.talentpitch.co/app/generics/companies/default_image_logo.png",
            "company_name": "TalentPitch Vacantes Externas",
            "compatibility": null,
            "compatibility_reason": null,
            "connected": false,
            "contract_type": "",
            "created_at": "09-10-2023",
            "creator": "",
            "description": "En este rol se requiere una persona con demasiada estructura, metodología, procesos, análisis de datos, geek, irreverente.",
            "desired_states": "[{\"icon\":\"https://media.interacpedia.com/app/work/want_employment.svg\",\"key\":\"employment\",\"label\":\"Employment\"},{\"icon\":\"https://media.interacpedia.com/app/work/want_first_job.svg\",\"key\":\"first_job\",\"label\":\"First job\"}]",
            "id": 491893,
            "image": "https://media.talentpitch.co/app/generics/thematics/tech/image_8.webp",
            "interest_areas": "",
            "level_experience": "0",
            "name": "LÍDER DE INTELIGENCIA DE MERCADOS",
            "optional_requirements": "",
            "pitches_count": 0,
            "presentation": false,
            "proposed_count": 0,
            "requirements": "",
            "review": 0,
            "salary": "Confidential",
            "selected_count": 0,
            "sent_pitch": false,
            "video": "https://media.talentpitch.co/challenges/491893/tmpdirect-upload-v1-6e452e87d4944d84a8d34c110968883f.mp4",
            "views_count": 34,
            "work_methods": ""
        }
        ],
        companyInformation: {
            companyIntereses: [
                {
                    title: "Areas de intres",
                    tags: ["copy", "copy"],
                },
                {
                    title: "Vacantes sugeridas por AI",
                    tags: ["copy", "copy"],
                },
            ],
            companyRequirements: [
                {
                    title: "Conocimientos",
                    tags: ["copy", "copy"],
                },
                {
                    title: "Habilidades",
                    tags: ["copy", "copy"],
                },
                {
                    title: "Herramientas",
                    tags: ["copy", "copy"],
                },
                {
                    title: "Metodologias",
                    tags: ["copy", "copy"],
                },
            ],
            companyLanguagesRequirements: [
                {
                    name: "Ingles",
                    level: "Avanzado",
                },
                {
                    name: "Frances",
                    level: "Avanzado",
                },
                {
                    name: "Aleman",
                    level: "Intermedio",
                },
            ],
            companyOffers: [
                {
                    title: "Beneficios que ofrecemos",
                    tags: ["copy", "copy"],
                },
                {
                    title: "Formas de trabajo que ofrecemos",
                    tags: ["copy", "copy"],
                },
                {
                    title: "Cultura que ofrecemos",
                    tags: ["copy", "copy"],
                },
                {
                    title: "Comunidades",
                    tags: ["copy", "copy"],
                },
            ]
        }
    },
    plugins: [vuexLocalStorage.plugin]
})